name: CustomMultiWorldPlugin
version: ${project.version}
main: ca.sajid.custommultiworldplugin.CustomMultiWorldPlugin
api-version: 1.16
authors: [ ShrimpyStuff, ElCholoGamer ]

commands:
  createworld:
    description: Creates a new world
    aliases: [ create ]
    usage: /<command> [name] [normal|nether|end] (AMPLIFIED|FLAT|LARGE_BIOMES)
    permission: cmwp.create
  deleteworld:
    description: Lets you delete a world
    aliases: [ delete ]
    usage: /<command> [name]
    permission: cmwp.delete

permissions:
  cmwp.*:
    description: Permission to use all CustomMultiWorldPlugin commands
    default: op
    children:
      cmwp.create:
        description: Permission to use the create command
      cmwp.delete:
        description: Permission to use the delete command
