name: CustomMultiWorldPlugin
version: ${project.version}
main: ca.sajid.custommultiworldplugin.CustomMultiWorldPlugin
api-version: 1.16
commands:
  createworld:
    description: Creates a new world
    aliases: [ create]
    usage: /<command> [name] [normal|nether|end] (AMPLIFIED|FLAT|LARGE_BIOMES)
    permission: cmwp.createworld

permissions:
  cmwp.*:
    description: Permission to use all CustomMultiWorldPlugin commands
    default: op
    children:
      cmwp.createworld:
        description: Permission to use the create command
